import { Product } from './store';

export const SAMPLE_PRODUCTS: Product[] = [
  {
    id: '1',
    name: 'Scorpion Tail Hoodie',
    description: 'Premium fleece hoodie with interlocking A / scorpion tail mark',
    price: 8500,
    image: 'https://images.unsplash.com/photo-1556821552-7f41c5d440db?w=500&h=600&fit=crop',
    category: 'Scorpion',
    stock: 42,
    color: 'Charcoal',
    size: 'M',
  },
  {
    id: '2',
    name: 'USMBA 1938 Tee',
    description: 'Heritage football culture tee — est. 1938 Bel Abbès',
    price: 4200,
    image: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=500&h=600&fit=crop',
    category: 'USMBA',
    stock: 88,
    color: 'Algeria Red',
    size: 'L',
  },
  {
    id: '3',
    name: 'Belabbès Varsity Jacket',
    description: 'Wool-blend varsity with venom accent stitching',
    price: 12500,
    image: 'https://images.unsplash.com/photo-1551028719-00167b16ebc5?w=500&h=600&fit=crop',
    category: 'Belabbès Streetwear',
    stock: 18,
    color: 'Black',
    size: 'M',
  },
  {
    id: '4',
    name: 'Cargo Pants',
    description: 'Utility cargo with reinforced pockets — desert-ready',
    price: 6800,
    image: 'https://images.unsplash.com/photo-1542272604-787c62d465d1?w=500&h=600&fit=crop',
    category: 'Belabbès Streetwear',
    stock: 35,
    color: 'Sand',
    size: 'M',
  },
  {
    id: '5',
    name: 'Algérie Crewneck',
    description: 'Warm crewneck celebrating local pride — Adel × Abdelillah',
    price: 5500,
    image: 'https://images.unsplash.com/photo-1576566588028-4147f3842f27?w=500&h=600&fit=crop',
    category: 'Algérie',
    stock: 56,
    color: 'Red',
    size: 'L',
  },
  {
    id: '6',
    name: 'Scorpion Snapback',
    description: 'Embroidered stinger dot cap — one size fits all',
    price: 3200,
    image: 'https://images.unsplash.com/photo-1588345921523-c2dcdb7f1dcd?w=500&h=600&fit=crop',
    category: 'Scorpion',
    stock: 120,
    color: 'Black',
    size: 'One Size',
  },
  {
    id: '7',
    name: 'Belabbès Coach Jacket',
    description: 'Lightweight nylon coach jacket with smile curve detail',
    price: 9200,
    image: 'https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=500&h=600&fit=crop',
    category: 'Belabbès Streetwear',
    stock: 24,
    color: 'Charcoal',
    size: 'L',
  },
  {
    id: '8',
    name: 'USMBA Track Top',
    description: 'Performance track top inspired by stadium culture',
    price: 7800,
    image: 'https://images.unsplash.com/photo-1620799140408-edc6dcb6d633?w=500&h=600&fit=crop',
    category: 'USMBA',
    stock: 31,
    color: 'Red/Black',
    size: 'M',
  },
];

export const COLLECTIONS = [
  'Scorpion',
  'USMBA',
  'Belabbès Streetwear',
  'Algérie',
];

export const WILAYAS = [
  {
    id: 'sidi-bel-abbes',
    name: 'Sidi Bel Abbès',
    homeDelivery: 400,
    stopDesk: 300,
    days: '2-3',
    communes: ['Sidi Bel Abbès', 'Telagh', 'Sfisef', 'Ain Tindamine', 'Makedra'],
  },
  {
    id: 'algiers',
    name: 'Alger',
    homeDelivery: 600,
    stopDesk: 450,
    days: '3-5',
    communes: ['Alger Centre', 'Bab El Oued', 'Kouba', 'Ouled Fayet', 'Hydra'],
  },
  {
    id: 'oran',
    name: 'Oran',
    homeDelivery: 500,
    stopDesk: 400,
    days: '2-4',
    communes: ['Oran', 'Sidi Lakhdar', 'El Mers', 'Es Senia', 'Bir El Djir'],
  },
  {
    id: 'constantine',
    name: 'Constantine',
    homeDelivery: 650,
    stopDesk: 500,
    days: '4-6',
    communes: ['Constantine', 'El Khroub', 'Ain Smara', 'Ibn Ziad'],
  },
  {
    id: 'annaba',
    name: 'Annaba',
    homeDelivery: 700,
    stopDesk: 550,
    days: '4-6',
    communes: ['Annaba', 'El Bouni', 'Sidi Amar', 'Berrahal'],
  },
  {
    id: 'blida',
    name: 'Blida',
    homeDelivery: 550,
    stopDesk: 400,
    days: '3-5',
    communes: ['Blida', 'Larbaa', 'Mouzaia', 'Soumaa'],
  },
  {
    id: 'tlemcen',
    name: 'Tlemcen',
    homeDelivery: 450,
    stopDesk: 350,
    days: '2-4',
    communes: ['Tlemcen', 'Sabra', 'Maghnia', 'Nedroma'],
  },
  {
    id: 'setif',
    name: 'Sétif',
    homeDelivery: 600,
    stopDesk: 450,
    days: '3-5',
    communes: ['Sétif', 'El Eulma', 'Ain Arnat', 'Ain Azel'],
  },
];
